---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: systemctl start snapd
  service:
    name: snapd
    state: started
    enabled: true
