@startuml
skinparam shadowing false

skinparam rectangle {
  roundCorner 25
  borderColor #F27C07
  backgroundColor #FFBC3F
  fontColor White
  BorderThickness 3
}

rectangle "192.168.33.10" <<wafu_ansible>> as wafu_ansible {
}

rectangle "192.168.33.11" <<mutsuki>> as mutsuki {
}
rectangle "192.168.33.12" <<kisaragi>> as kisaragi {
}
rectangle "192.168.33.13" <<yayoi>> as yayoi {
}

wafu_ansible -do-> mutsuki
wafu_ansible -do-> kisaragi
wafu_ansible -do-> yayoi
@enduml
