---

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: 'Install direnv({{ direnv_version }})'
  become: yes
  get_url:
    url: 'https://github.com/direnv/direnv/releases/download/{{ direnv_version }}/direnv.linux-amd64'
    dest: /usr/local/bin/direnv
    mode: 0755
    headers:
      Accept: '*/*'
