---

- include_tasks: amazonlinux1-2.yml
  when: ansible_distribution == 'Amazon'

- include_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: dockerグループにvagrant userを追加
  become: yes
  user:
    name: vagrant
    groups: docker
